# Generated by Django 5.0.3 on 2024-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ename", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("create_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "MyAccounts",
            },
        ),
    ]
