# Generated by Django 5.0.3 on 2024-04-14 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyAccounts",
        ),
    ]
